### ISSUE TITLE
Not compatible with your version of pluck

### ISSUE THREAD

**Issue by 2braincells2go** [pluck-cms/simple#1]
New pluck users and attempting to learn modules.

I follow instructions from readme and get error:

"This module is not compatible with your version of pluck, and has been disabled."

Running Pluck V 4.7.3

Something I am doing wrong or is site/pluck out of date?

Thanks!

**Comment by ekyo-pl** [comment]
modify simple.php file.
change 'compatibility' => '4.7'
into 'compatibility' => '4.7.3'

This should work.

**Comment by 2braincells2go** [comment]
Thanks for tip @ekyo-pl.

I had tried that and still got the message not compatible. Seems Pluck has changed since released.

Cannot create branch or push, but changes needed to work with my 4.7.3:

//{plugin}_info
  function simple_info() {
    global $lang;
    $module_info = array(
        'name'          => $lang['simple']['name'],
        'intro'         => $lang['simple']['intro'],
        'version'       => '0.2',
        'author'        => $lang['simple']['author'],
        'website'       => 'http://twitter.com/grwebguy',
        'compatibility' => '4.7.3'
    );
    return $module_info;
 }
